# Generated by Django 3.2.18 on 2023-04-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='song',
            name='unique_user_song_title',
        ),
    ]
