# Generated by Django 3.2.18 on 2023-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0002_remove_song_unique_user_song_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_user_song_title'),
        ),
    ]
