# Generated by Django 3.2.18 on 2023-04-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0003_song_unique_user_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
