# Generated by Django 3.2.18 on 2023-04-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0004_alter_song_artist'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='song',
            name='unique_user_song_title',
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_song_title'),
        ),
    ]
