# Generated by Django 3.2.18 on 2023-04-01 20:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songbook', '0005_auto_20230401_1959'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='song',
            name='unique_user_song_title',
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('user', 'title')},
        ),
    ]
