# Generated by Django 3.2.18 on 2023-04-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0006_auto_20230401_2005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set(),
        ),
    ]
