# Generated by Django 3.2.18 on 2023-04-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0008_auto_20230401_2035'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='song',
            name='unique_user_song_title',
        ),
    ]
