# Generated by Django 3.2.18 on 2023-04-01 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0009_remove_song_unique_user_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
