# Generated by Django 3.2.18 on 2023-04-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0010_song_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='created_on',
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_song_title'),
        ),
    ]
