# Generated by Django 3.2.18 on 2023-04-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0011_auto_20230402_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_slug',
            new_name='slug',
        ),
    ]
