# Generated by Django 3.2.18 on 2023-04-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0012_rename_song_slug_song_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='song',
            name='unique_user_song_title',
        ),
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
    ]
