# Generated by Django 3.2.18 on 2023-04-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0014_setlist'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_song_title'),
        ),
    ]
