# Generated by Django 3.2.18 on 2023-04-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0015_song_unique_user_song_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='setlist',
            constraint=models.UniqueConstraint(fields=('user', 'setlist_name'), name='unique_user_setlist_name'),
        ),
    ]
