# Generated by Django 3.2.18 on 2023-04-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0016_setlist_unique_user_setlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='scroll_speed',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
