# Generated by Django 3.2.18 on 2023-04-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0017_song_scroll_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='scroll_speed',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
